import Foundation

/// Which of an item's files this app could actually open.
///
/// An archive.org item is not one file. A scanned comic uploaded as a 300 MB
/// CBR arrives with a dozen siblings the archive derived from it — an OCR'd
/// PDF, a JPEG 2000 zip, an EPUB, four kinds of text layer, a torrent and a
/// handful of metadata documents — and picking the wrong one is the difference
/// between a comic and a quarter of a gigabyte of nothing.
///
/// So the reader is shown a choice rather than given a guess, and this decides
/// what goes on that list. Two things are ruled out for good:
///
///  * **JPEG 2000.** `_jp2.zip` is the archive's own page pipeline output and
///    the largest file most items hold — 247 MB against 28 MB for the same
///    comic as a PDF. iOS's ImageIO cannot decode JPEG 2000 at all, so it
///    would download in full and render as blank pages.
///  * **Torrents.** Every item has an `_archive.torrent`, generated by the
///    archive whether or not anyone wants one, so its presence says nothing
///    about an item. There is no BitTorrent client here and there is not going
///    to be one; every file a torrent carries is served over HTTPS anyway.
public extension ArchiveOrgItem {

    /// One file an issue could be read from.
    struct ReadableFile: Equatable, Sendable, Identifiable {
        /// The file's name inside the item, as its uploader typed it.
        public let name: String
        public let kind: Kind
        /// What the archive says it weighs. Recorded against the mirror, which
        /// is what lets a download too large for the device be refused before
        /// a byte of it moves.
        public let bytes: Int64?

        /// Unique within an item, which is all this identity is for.
        public var id: String { name }

        public init(name: String, kind: Kind, bytes: Int64?) {
            self.name = name; self.kind = kind; self.bytes = bytes
        }

        /// Where it lives, relative to `ArchiveOrg.base`.
        public func path(item: String) -> String {
            ArchiveOrg.path(item: item, file: name)
        }

        public func url(item: String) -> String {
            ArchiveOrg.base + path(item: item)
        }

        /// What the format is called, off the name rather than the archive's
        /// own word for it: "CBR" is what a reader recognises, where "Comic
        /// Book RAR" is what the archive files it under.
        public var label: String {
            let ext = (name as NSString).pathExtension.uppercased()
            return ext.isEmpty ? kind.label : ext
        }
    }

    /// The kinds worth offering, in the order they are offered.
    ///
    /// Quality first, because the size is shown beside every one of them and
    /// that is the trade-off the reader is being asked to make: the uploaded
    /// scan is what the scanner produced, and the text PDF is that same scan
    /// re-compressed around an OCR layer at roughly a tenth of the bytes and
    /// visibly softer.
    enum Kind: Int, Sendable, Comparable, CaseIterable {
        /// A CBR or CBZ, as uploaded.
        case comicBook
        /// "Image Container PDF" — a PDF that is pages of images, which is
        /// what a scan uploaded as a PDF is.
        case scan
        /// A plain zip, rar or 7z upload that nobody labelled a comic.
        case container
        /// "Text PDF" — the archive's own derivative, with searchable text.
        case text

        public static func < (a: Kind, b: Kind) -> Bool { a.rawValue < b.rawValue }

        /// Fallback name for a file with no extension at all.
        var label: String {
            switch self {
            case .comicBook, .container: return "Archive"
            case .scan, .text:           return "PDF"
            }
        }

        /// The half-sentence under the name in the picker.
        public var detail: String {
            switch self {
            case .comicBook, .scan, .container: return "as uploaded"
            case .text:                         return "searchable text, smaller"
            }
        }
    }

    /// What this item can be read from, best first.
    ///
    /// Empty is the answer that matters: it is what greys out Import, and it
    /// is the truth for a collection page, a lending-restricted book, an audio
    /// item, and for the single-PNG items that a scanner uploads one cover at
    /// a time.
    var readableFiles: [ReadableFile] {
        files.compactMap { file in
            Self.kind(of: file).map {
                ReadableFile(name: file.name, kind: $0, bytes: file.bytes)
            }
        }
        .sorted { ($0.kind, $0.name) < ($1.kind, $1.name) }
    }

    /// Whether the archive has run its page pipeline over this item.
    ///
    /// Which is exactly the question "will the BookReader cover endpoint
    /// answer for it" — `/page/n0_w1024.jpg` is served out of those
    /// derivatives, and an item that has none 404s. Asking it here costs
    /// nothing; asking it over the network would cost a request per item
    /// browsed to.
    var hasRenderedPages: Bool {
        files.contains { file in
            let format = (file.format ?? "").lowercased()
            return format.contains("jp2") || format == "scandata"
        }
    }

    /// The best cover available without downloading the issue.
    ///
    /// The item's own first page where the archive can render one, and its
    /// square tile where it cannot. Nil when the item has neither, which
    /// leaves the shelf drawing its placeholder until the download arrives and
    /// the issue's own first page replaces it.
    var coverPath: String? {
        if hasRenderedPages { return ArchiveOrg.firstPagePath(item: identifier) }
        guard files.contains(where: { $0.name == "__ia_thumb.jpg" }) else { return nil }
        return ArchiveOrg.thumbnailPath(item: identifier)
    }

    // MARK: - Classification

    /// The archive's own word for a file, where it names one this app wants.
    ///
    /// Matched on the format rather than the extension because the format is
    /// the only thing that separates an uploaded scan from a derivative made
    /// out of it: `VC OP - Zagor - 007.PDF` and `VC OP - Zagor - 007.pdf` sit
    /// in the same item, differ by one letter of case, and are 264 MB and
    /// 23 MB of quite different things.
    private static let knownFormats: [String: Kind] = [
        "comic book rar": .comicBook,
        "comic book zip": .comicBook,
        "image container pdf": .scan,
        "text pdf": .text,
        "additional text pdf": .text,
    ]

    /// The fallback, for an upload the archive never classified.
    private static let knownExtensions: [String: Kind] = [
        "cbr": .comicBook, "cbz": .comicBook, "cb7": .comicBook,
        "pdf": .scan,
        "zip": .container, "rar": .container, "7z": .container,
    ]

    /// Words that mark a format as one of the archive's by-products rather
    /// than the thing itself.
    ///
    /// Consulted only after `knownFormats` has had its say, so "Text PDF" is
    /// admitted before "ocr" gets a chance to reject it.
    private static let byProductWords = [
        "torrent", "metadata", "thumb", "item tile", "jp2", "djvu", "ocr",
        "epub", "json", "xml", "log", "checksums", "gif", "png", "jpeg",
    ]

    /// Names the archive gives its derivatives, for a file whose format it
    /// somehow never recorded.
    ///
    /// `_jp2.zip` is the one that matters: with no format to reject it, the
    /// extension map would read it as a plain zip and offer a quarter of a
    /// gigabyte of undecodable pages.
    private static let byProductSuffixes = [
        "_jp2.zip", "_jp2.tar", "_djvu.txt", "_djvu.xml", "_hocr.html",
        "_chocr.html.gz", "_hocr_searchtext.txt.gz", "_hocr_pageindex.json.gz",
        "_scandata.xml", "_page_numbers.json", "_files.xml", "_meta.xml",
        "_meta.sqlite", "_archive.torrent", "_thumb.jpg", "__ia_thumb.jpg",
    ]

    /// What one file is, or nil if it is nothing this app can open.
    ///
    /// Positive matching throughout: a file is offered because it was
    /// recognised, never because nothing objected to it. An item full of
    /// formats nobody here has heard of yields an empty list and a clear
    /// "nothing to import", which is a much better failure than a download of
    /// something unopenable.
    static func kind(of file: File) -> Kind? {
        // A zero-byte file is a file the upload lost.
        if let bytes = file.bytes, bytes <= 0 { return nil }
        let format = (file.format ?? "").lowercased()
        if let known = knownFormats[format] { return known }
        if byProductWords.contains(where: format.contains) { return nil }
        let name = file.name.lowercased()
        if byProductSuffixes.contains(where: name.hasSuffix) { return nil }
        return knownExtensions[(name as NSString).pathExtension]
    }
}
