import Foundation

/// Which of an item's files this app could actually open.
///
/// An archive.org item is not one file. A scanned comic uploaded as a 300 MB
/// CBR arrives with a dozen siblings the archive derived from it — an OCR'd
/// PDF, a JPEG 2000 zip, an EPUB, four kinds of text layer, a torrent and a
/// handful of metadata documents — and picking the wrong one is the difference
/// between a comic and a quarter of a gigabyte of nothing.
///
/// So the reader is shown a choice rather than given a guess, and this decides
/// what goes on that list. Two things are ruled out for good:
///
///  * **JPEG 2000.** `_jp2.zip` is the archive's own page pipeline output and
///    the largest file most items hold — 247 MB against 28 MB for the same
///    comic as a PDF. iOS's ImageIO cannot decode JPEG 2000 at all, so it
///    would download in full and render as blank pages.
///  * **Torrents.** Every item has an `_archive.torrent`, generated by the
///    archive whether or not anyone wants one, so its presence says nothing
///    about an item. There is no BitTorrent client here and there is not going
///    to be one; every file a torrent carries is served over HTTPS anyway.
public extension ArchiveOrgItem {

    /// One file an issue could be read from.
    struct ReadableFile: Equatable, Sendable, Identifiable {
        /// The file's name inside the item, as its uploader typed it.
        public let name: String
        public let kind: Kind
        /// What the archive says it weighs. Recorded against the mirror, which
        /// is what lets a download too large for the device be refused before
        /// a byte of it moves.
        public let bytes: Int64?
        /// Whether this is what somebody uploaded, rather than something the
        /// archive made out of it.
        public let isOriginal: Bool

        /// Unique within an item, which is all this identity is for.
        public var id: String { name }

        public init(name: String, kind: Kind, bytes: Int64?, isOriginal: Bool) {
            self.name = name; self.kind = kind; self.bytes = bytes
            self.isOriginal = isOriginal
        }

        /// The half-sentence under the name in the picker.
        ///
        /// Says where the file came from and nothing about how big it is. It
        /// used to call the archive's PDF "smaller", which is true of most
        /// items and was wrong by two orders of magnitude on the first one
        /// anybody tried it on: Byte's September 1986 issue is a 330 MB PDF
        /// beside a 1 MB accessibility package. The size is printed next to
        /// this, measured; a word that guesses at it can only disagree with
        /// the number beside it.
        public var detail: String {
            if isOriginal { return "as uploaded" }
            return kind == .text ? "searchable text" : "made by archive.org"
        }

        /// Where it lives, relative to `ArchiveOrg.base`.
        public func path(item: String) -> String {
            ArchiveOrg.path(item: item, file: name)
        }

        public func url(item: String) -> String {
            ArchiveOrg.base + path(item: item)
        }

        /// What the format is called, off the name rather than the archive's
        /// own word for it: "CBR" is what a reader recognises, where "Comic
        /// Book RAR" is what the archive files it under.
        public var label: String {
            let ext = (name as NSString).pathExtension.uppercased()
            return ext.isEmpty ? kind.label : ext
        }
    }

    /// The kinds worth offering, in the order they are offered.
    ///
    /// Quality first, because the size is shown beside every one of them and
    /// that is the trade-off the reader is being asked to make: the uploaded
    /// scan is what the scanner produced, and the text PDF is that same scan
    /// re-compressed around an OCR layer at roughly a tenth of the bytes and
    /// visibly softer.
    enum Kind: Int, Sendable, Comparable, CaseIterable {
        /// A CBR or CBZ, as uploaded.
        case comicBook
        /// "Image Container PDF" — a PDF that is pages of images, which is
        /// what a scan uploaded as a PDF is.
        case scan
        /// A plain zip, rar or 7z upload that nobody labelled a comic.
        case container
        /// "Text PDF" — the archive's own derivative, with searchable text.
        case text

        public static func < (a: Kind, b: Kind) -> Bool { a.rawValue < b.rawValue }

        /// Fallback name for a file with no extension at all.
        var label: String {
            switch self {
            case .comicBook, .container: return "Archive"
            case .scan, .text:           return "PDF"
            }
        }
    }

    /// Item kinds this app will not import from, whatever files they hold.
    ///
    /// The one place a file's own evidence runs out. "In Search of the Most
    /// Amazing Thing" is an Apple II game whose upload is two plain `ZIP`s,
    /// marked `original`, and nothing about a zip says whether it holds
    /// scanned pages or disk images. The item says: `mediatype: software`.
    /// The same goes for the zip beside a concert recording or a film.
    ///
    /// A deny-list rather than "texts only", deliberately. Uploaders file
    /// scans under `image` and `data` as well — the mediatype is a menu choice
    /// on an upload form, not a fact — and refusing everything unfamiliar
    /// would make perfectly readable issues unimportable with no way for
    /// anyone to say otherwise. These four are the ones that are never a
    /// scanned issue.
    static let unreadableMediatypes: Set<String> = [
        "software", "audio", "movies",
        // The archive's own name for live music, and audio by another word.
        "etree",
    ]

    /// What this item can be read from, best first.
    ///
    /// Empty is the answer that matters: it is what greys out Import, and it
    /// is the truth for a collection page, a lending-restricted book, a game,
    /// a concert, and for the single-PNG items that a scanner uploads one
    /// cover at a time.
    var readableFiles: [ReadableFile] {
        guard !Self.unreadableMediatypes.contains(mediatype ?? "") else { return [] }
        return files.compactMap { file in
            Self.kind(of: file).map {
                ReadableFile(name: file.name, kind: $0, bytes: file.bytes,
                             isOriginal: file.source == .original)
            }
        }
        .sorted { ($0.kind, $0.name) < ($1.kind, $1.name) }
    }

    /// One issue, and the formats it can be read in.
    ///
    /// An archive.org item is not always one issue. `transactor-for-the-amiga`
    /// is a "magazine pack": one item, thirteen issues of Transactor, a PDF
    /// each. Treating the item as the issue offered those thirteen as thirteen
    /// identical-looking "PDF · as uploaded" rows, and importing any two of
    /// them wrote the same library row twice — the second silently replacing
    /// the first.
    struct ReadableIssue: Equatable, Sendable, Identifiable {
        /// The filename its files share, without extension. This is what the
        /// archive's reader puts in the URL, and what identifies the issue
        /// inside the item.
        public let stem: String
        /// Its formats, best first. Never empty.
        public let files: [ReadableFile]

        public var id: String { stem }
        /// What to offer when no choice of format is being made.
        public var best: ReadableFile { files[0] }

        public init(stem: String, files: [ReadableFile]) {
            self.stem = stem; self.files = files
        }

        /// The stem as a person would read it: underscores undone and the
        /// archive's own tags dropped, so
        /// `Transactor_for_the_Amiga_Vol_01_01_1988_Apr[ocr]` reads as
        /// "Transactor for the Amiga Vol 01 01 1988 Apr".
        public var name: String { ArchiveOrgItem.readableName(stem) }
    }

    /// The issues this item holds, oldest name first.
    ///
    /// Grouped by filename stem, which is exactly the distinction that matters
    /// and the one an extension cannot make: `Zagor 137….cbr` and
    /// `Zagor 137….pdf` are two formats of one issue, while
    /// `…Vol_01_01….pdf` and `…Vol_01_02….pdf` are two issues.
    var readableIssues: [ReadableIssue] {
        var order: [String] = []
        var stems: [String: String] = [:]          // folded key -> stem as written
        var grouped: [String: [ReadableFile]] = [:]
        for file in readableFiles {
            let stem = Self.stem(of: file.name)
            let key = stem.lowercased()
            if grouped[key] == nil {
                order.append(key)
                stems[key] = stem
            }
            grouped[key, default: []].append(file)
        }
        return order
            .map { ReadableIssue(stem: stems[$0] ?? $0, files: grouped[$0] ?? []) }
            .sorted { $0.stem.localizedStandardCompare($1.stem) == .orderedAscending }
    }

    /// The issue a file belongs to.
    func issue(holding file: ReadableFile) -> ReadableIssue? {
        let key = Self.stem(of: file.name).lowercased()
        return readableIssues.first { $0.stem.lowercased() == key }
    }

    /// The issue an address names, when it names one this item holds.
    func issue(named stem: String) -> ReadableIssue? {
        let key = stem.lowercased()
        return readableIssues.first { $0.stem.lowercased() == key }
    }

    /// How one issue of this item is filed in the library.
    ///
    /// An item holding one issue *is* that issue, and keeps the identifier as
    /// its key — which is what lets a reader who browses to A-Profy find the
    /// copy the shipped catalogue already gave them. An item holding several
    /// has to name which, or the second import overwrites the first.
    func code(for issue: ReadableIssue) -> String {
        readableIssues.count > 1 ? "\(identifier)/\(issue.stem)" : identifier
    }

    /// Whether the archive has run its page pipeline over one issue.
    ///
    /// Which is exactly the question "will the BookReader cover endpoint
    /// answer for it" — `/page/n0_w1024.jpg` is served out of those
    /// derivatives, and an item that has none 404s. Asking it here costs
    /// nothing; asking it over the network would cost a request per item.
    ///
    /// Per issue, not per item, and that is the whole point on a pack: the
    /// archive scanned Transactor's first volume and left the other twelve as
    /// plain PDFs, so the item answers `/page/n0` with volume one's cover —
    /// which is the right cover for exactly one of the thirteen.
    func hasRenderedPages(forStem stem: String) -> Bool {
        let prefix = stem.lowercased()
        return files.contains { file in
            let format = (file.format ?? "").lowercased()
            guard format.contains("jp2") || format == "scandata" else { return false }
            return file.name.lowercased().hasPrefix(prefix)
        }
    }

    /// The best cover available without downloading the issue.
    ///
    /// The issue's own first page where the archive can render one, and the
    /// item's square tile where it cannot — but the tile belongs to the item,
    /// so a pack's members get nothing rather than thirteen copies of volume
    /// one's cover. Nil leaves the shelf drawing its placeholder until the
    /// download arrives and the issue's own first page replaces it, which is
    /// the truth in the meantime.
    func coverPath(for issue: ReadableIssue) -> String? {
        if hasRenderedPages(forStem: issue.stem) {
            return ArchiveOrg.firstPagePath(item: identifier)
        }
        guard readableIssues.count == 1,
              files.contains(where: { $0.name == "__ia_thumb.jpg" }) else { return nil }
        return ArchiveOrg.thumbnailPath(item: identifier)
    }

    /// A filename without its extension.
    static func stem(of name: String) -> String {
        (name as NSString).deletingPathExtension
    }

    /// Tags the archive appends to a scan's name — `[ocr]`, `[b&w]`.
    private static let scanTag = Rx(#"\[[^\]]*\]"#)
    private static let spaceRun = Rx(#"\s+"#)

    /// A filename stem as a person would read it.
    static func readableName(_ stem: String) -> String {
        var text = stem.replacingOccurrences(of: "_", with: " ")
        text = scanTag.replacing(text, with: " ")
        text = spaceRun.replacing(text, with: " ")
        return text.trimmingCharacters(in: .whitespaces)
    }

    /// An issue's name with the part the whole item already says trimmed off.
    ///
    /// Every file in a pack repeats the magazine's name, and the picker states
    /// that once in its heading — so thirteen rows reading "Transactor for the
    /// Amiga Vol 01 01 1988 Apr" differ only in their last few words, which is
    /// exactly where the eye is not looking. Trimmed, they read "Vol 01 01
    /// 1988 Apr".
    ///
    /// Only leading words, and only ones the title actually has: an issue
    /// whose name shares nothing with the item's keeps all of it.
    func shortName(for issue: ReadableIssue) -> String {
        let words = Self.readableName(issue.name).split(separator: " ").map(String.init)
        let titleWords = Fold.fold(title).split(separator: " ").map(String.init)
        var index = 0
        while index < words.count, index < titleWords.count,
              Fold.fold(words[index]) == titleWords[index] {
            index += 1
        }
        let kept = words.dropFirst(index).joined(separator: " ")
        return kept.isEmpty ? issue.name : kept
    }

    // MARK: - Classification

    /// The archive's own word for a file, where it names one this app wants.
    ///
    /// Matched on the format rather than the extension because the format is
    /// the only thing that separates an uploaded scan from a derivative made
    /// out of it: `VC OP - Zagor - 007.PDF` and `VC OP - Zagor - 007.pdf` sit
    /// in the same item, differ by one letter of case, and are 264 MB and
    /// 23 MB of quite different things.
    private static let knownFormats: [String: Kind] = [
        "comic book rar": .comicBook,
        "comic book zip": .comicBook,
        "image container pdf": .scan,
        "text pdf": .text,
        "additional text pdf": .text,
    ]

    /// The fallback, for an upload the archive never classified.
    private static let knownExtensions: [String: Kind] = [
        "cbr": .comicBook, "cbz": .comicBook, "cb7": .comicBook,
        "pdf": .scan,
        "zip": .container, "rar": .container, "7z": .container,
    ]

    /// Words that mark a format as one of the archive's by-products rather
    /// than the thing itself.
    ///
    /// Consulted only after `knownFormats` has had its say, so "Text PDF" is
    /// admitted before "ocr" gets a chance to reject it.
    private static let byProductWords = [
        "torrent", "metadata", "thumb", "item tile", "jp2", "djvu", "ocr",
        "epub", "json", "xml", "log", "checksums", "gif", "png", "jpeg",
    ]

    /// Names the archive gives its derivatives, for a file whose format it
    /// somehow never recorded.
    ///
    /// `_jp2.zip` is the one that matters: with no format to reject it, the
    /// extension map would read it as a plain zip and offer a quarter of a
    /// gigabyte of undecodable pages.
    private static let byProductSuffixes = [
        "_jp2.zip", "_jp2.tar", "_djvu.txt", "_djvu.xml", "_hocr.html",
        "_chocr.html.gz", "_hocr_searchtext.txt.gz", "_hocr_pageindex.json.gz",
        "_scandata.xml", "_page_numbers.json", "_files.xml", "_meta.xml",
        "_meta.sqlite", "_archive.torrent", "_thumb.jpg", "__ia_thumb.jpg",
    ]

    /// The only things the archive *derives* that are worth reading.
    ///
    /// A strict allow-list, and the point is what it excludes. Everything an
    /// item holds beyond the upload was generated by the archive's pipeline —
    /// JPEG 2000 pages, an EPUB, a DjVu, four text layers, an animated GIF, a
    /// DAISY accessibility package — and only one of them is a readable copy
    /// of the magazine. Judging those by extension is what offered Byte's
    /// September 1986 issue as a 1 MB "ZIP, as uploaded" that was neither: it
    /// was `_daisy.zip`, a bundle of navigation XML with no pages in it.
    ///
    /// So a derivative has to be named here to be offered, and a format the
    /// archive invents next year is refused until somebody looks at it.
    private static let readableDerivatives: [String: Kind] = [
        "text pdf": .text,
        "additional text pdf": .text,
        // Vanishingly rare as a derivative, and admitted because an item whose
        // upload has been replaced by one is still a readable scan.
        "image container pdf": .scan,
    ]

    /// What one file is, or nil if it is nothing this app can open.
    ///
    /// Positive matching throughout: a file is offered because it was
    /// recognised, never because nothing objected to it. An item full of
    /// formats nobody here has heard of yields an empty list and a clear
    /// "nothing to import", which is a much better failure than a download of
    /// something unopenable.
    static func kind(of file: File) -> Kind? {
        // A zero-byte file is a file the upload lost.
        if let bytes = file.bytes, bytes <= 0 { return nil }
        let format = (file.format ?? "").lowercased()

        switch file.source {
        case .metadata:
            // The archive's own bookkeeping: the torrent, the XML, the sqlite.
            return nil
        case .derivative:
            return readableDerivatives[format]
        case .original:
            break
        }

        // An upload is judged on what it is. The by-product checks still earn
        // their place here, because "original" covers the item tile and the
        // files.xml as well as the scan.
        if let known = knownFormats[format] { return known }
        if byProductWords.contains(where: format.contains) { return nil }
        let name = file.name.lowercased()
        if byProductSuffixes.contains(where: name.hasSuffix) { return nil }
        return knownExtensions[(name as NSString).pathExtension]
    }
}
